# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
    - id: poetry-check
    - id: poetry-lock
#    - id: poetry-export
    - id: poetry-install
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-added-large-files
    -   id: forbid-submodules
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
- repo: https://github.com/iamthefij/docker-pre-commit
  rev: master
  hooks:
  - id: docker-compose-check
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.0
  hooks:
  - id: actionlint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.4
  hooks:
  - id: ruff
  - id: ruff-format
