repo_url: https://github.com/jessepinkman9900/jessepinkman9900.github.io/
site_name: jessepinkman9900
docs_dir: docs
edit_uri: blob/main/docs/

theme:
  name: simple-blog

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About: about.md
